### DISCUSSION TITLE
Bug fix for `node gyp` error on GitHub Actions

### DISCUSSION THREAD

**Discussion by RobertGemmaJr** [brown-ccv/honeycomb#316] [Announcements]
## The Issue

The latest version(s) of GitHub's runners have been updated to a newer version of Python that is incompatible with Honeycomb's internal dependencies. The change should not effect any local development environments but DOES break the various actions used to build and package the application on GitHub. The action workflows need to be updated to resolve this bug.

## The Fix

We must instruct GitHub to use Python version 3.10 in the workflows. This is done with the following code:

```yml
      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
```

## Final Solution

The above action must be added to any workflow in which we call `npm ci` or `npm install`

1. [pull_request.yml](https://github.com/brown-ccv/honeycomb/blob/v3.2.3/.github/workflows/pull_request.yml) (`build.yml` in older versions of Honeycomb)
2. [workflow-package.yml](https://github.com/brown-ccv/honeycomb/blob/v3.2.3/.github/workflows/workflow-package.yml) (`package.yml` in older versions of Honeycomb)
3. [release.yaml](https://github.com/brown-ccv/honeycomb/blob/v3.2.3/.github/workflows/release.yml)
4. _Older versions of Honeycomb may also have a `release-home-video.yaml` workflow_

The step should be inserted after the `setup-node` step and before the `Install Dependencies` step:

```yaml
# THIS SHOULD ALREADY BE IN YOUR ACTION
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

# ADD THIS!
      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

# THIS SHOULD ALSO BE IN YOUR ACTION
      # Install dependencies and set up environment
      - name: 📥 Install Dependencies
        run: npm ci
```

## New Output

Your workflow runs will now look like this:

![image](https://github.com/brown-ccv/honeycomb/assets/38439940/2ec47161-d782-4a90-9279-a31993f86340)
